name: powersoft_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.0
  pdf: ^3.10.4
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  share: ^2.0.4
  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/powersoft.png
